---
title: "Homework 6"
author: "Hertzbert Casseus"
date: "11/9/2020"
group: Neshma and Fareha
---

load("acs2017_ny_data.RData")
attach(acs2017_ny)
model_v3 <- lm(INCWAGE ~ AGE, data = acs2017_ny)
detach()
acs2017_ny$LABFORCE <- as.factor(acs2017_ny$LABFORCE)
levels(acs2017_ny$LABFORCE) <- c("NA","Not in LF","in LF")
acs2017_ny$MARST <- as.factor(acs2017_ny$MARST)
levels(acs2017_ny$MARST) <- c("married spouse present","married spouse absent","separated","divorced","widowed","never married")
acs2017_ny$age_bands <- cut(acs2017_ny$AGE,breaks=c(0,25,35,45,55,65,100))
table(acs2017_ny$age_bands,acs2017_ny$LABFORCE)

#This specific logit model allows us to analyze data of women and the workforce.

NA Not in LF in LF
(0,25]   31680     11717 13256
(25,35]      0      4271 20523
(35,45]      0      4064 18924
(45,55]      0      5406 21747
(55,65]      0     10563 18106
(65,100]     0     28701  5880

#The value above expresses the amount of women associatesd of whom are or arent in the workforce/laborforce. We see that women in the laborforce is highest for ages 25-35 & 45-55. It's at it's lowest past typical retirement age (65+).

pick_use1 <- (acs2017_ny$AGE >25) & (acs2017_ny$AGE <= 55)
dat_use1 <- subset(acs2017_ny, pick_use1)
dat_use1$LABFORCE <- droplevels(dat_use1$LABFORCE) # actually not necessary since logit is smart enough to drop unused levels, but helps my personal sense of order
model_logit1 <- glm(LABFORCE ~ AGE,
family = binomial, data = dat_use1)
model_logit1 <- glm(LABFORCE ~ AGE + I(AGE^2) + female + AfAm + Asian + race_oth + Hispanic
+ educ_hs + educ_somecoll + educ_college + educ_advdeg
+ MARST,
family = binomial, data = dat_use1)
summary(model_logit1)

Call:
  glm(formula = LABFORCE ~ AGE + I(AGE^2) + female + AfAm + Asian + 
        race_oth + Hispanic + educ_hs + educ_somecoll + educ_college + 
        educ_advdeg + MARST, family = binomial, data = dat_use1)

Deviance Residuals: 
  Min       1Q   Median       3Q      Max  
-2.6277   0.3476   0.4862   0.6459   1.5245  

Coefficients:
  Estimate Std. Error z value Pr(>|z|)    
(Intercept)                 0.6023215  0.2445543   2.463  0.01378 *  
  AGE                         0.0171486  0.0121072   1.416  0.15666    
I(AGE^2)                   -0.0003149  0.0001471  -2.141  0.03228 *  
  female                     -0.6839386  0.0205171 -33.335  < 2e-16 ***
  AfAm                       -0.1906696  0.0282354  -6.753 1.45e-11 ***
  Asian                      -0.1112229  0.0374503  -2.970  0.00298 ** 
  race_oth                   -0.0781864  0.0332004  -2.355  0.01852 *  
  Hispanic                    0.1653724  0.0313524   5.275 1.33e-07 ***
  educ_hs                     0.8972780  0.0310196  28.926  < 2e-16 ***
  educ_somecoll               1.4531782  0.0350710  41.435  < 2e-16 ***
  educ_college                1.9430903  0.0370924  52.385  < 2e-16 ***
  educ_advdeg                 2.3676171  0.0437358  54.135  < 2e-16 ***
  MARSTmarried spouse absent -0.5222011  0.0517449 -10.092  < 2e-16 ***
  MARSTseparated             -0.1240651  0.0577062  -2.150  0.03156 *  
  MARSTdivorced               0.0619381  0.0375785   1.648  0.09930 .  
MARSTwidowed               -0.3023247  0.0934446  -3.235  0.00121 ** 
  MARSTnever married         -0.3857612  0.0241093 -16.000  < 2e-16 ***
  ---
  Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

Null deviance: 71408  on 74934  degrees of freedom
Residual deviance: 64847  on 74918  degrees of freedom
AIC: 64881

Number of Fisher Scoring iterations: 5

#I attempted the model twice, in the second only focusing on whether the education was more of factor of women being in the labor force as opposed to including marital status and ethnic background.


model_logit2 <- glm(LABFORCE ~ AGE + I(AGE^2) + female + educ_hs + educ_somecoll + educ_college + educ_advdeg,
                    family = binomial, data = dat_use1)
summary(model_logit2)

Call:
  glm(formula = LABFORCE ~ AGE + I(AGE^2) + female + educ_hs + 
        educ_somecoll + educ_college + educ_advdeg, family = binomial, 
      data = dat_use1)

Deviance Residuals: 
  Min       1Q   Median       3Q      Max  
-2.4719   0.3314   0.4991   0.6618   1.2776  

Coefficients:
  Estimate Std. Error z value Pr(>|z|)    
(Intercept)   -0.4643898  0.2365864  -1.963   0.0497 *  
  AGE            0.0524913  0.0118990   4.411 1.03e-05 ***
  I(AGE^2)      -0.0006592  0.0001451  -4.542 5.57e-06 ***
  female        -0.6610114  0.0202820 -32.591  < 2e-16 ***
  educ_hs        0.9166319  0.0301345  30.418  < 2e-16 ***
  educ_somecoll  1.4906814  0.0339862  43.861  < 2e-16 ***
  educ_college   1.9778212  0.0357942  55.255  < 2e-16 ***
  educ_advdeg    2.4263440  0.0423324  57.317  < 2e-16 ***
  ---
  Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

Null deviance: 71408  on 74934  degrees of freedom
Residual deviance: 65339  on 74927  degrees of freedom
AIC: 65355

Number of Fisher Scoring iterations: 5

require(stargazer)
stargazer(model_logit1, type = "text")

======================================================
  Dependent variable:    
  ---------------------------
  LABFORCE          
------------------------------------------------------
  AGE                                   0.017           
(0.012)          

I(AGE2)                             -0.0003**         
  (0.0001)          

female                              -0.684***         
  (0.021)          

AfAm                                -0.191***         
  (0.028)          

Asian                               -0.111***         
  (0.037)          

race_oth                            -0.078**          
  (0.033)          

Hispanic                            0.165***          
  (0.031)          

educ_hs                             0.897***          
  (0.031)          

educ_somecoll                       1.453***          
  (0.035)          

educ_college                        1.943***          
  (0.037)          

educ_advdeg                         2.368***          
  (0.044)          

MARSTmarried spouse absent          -0.522***         
  (0.052)          

MARSTseparated                      -0.124**          
  (0.058)          

MARSTdivorced                        0.062*           
  (0.038)          

MARSTwidowed                        -0.302***         
  (0.093)          

MARSTnever married                  -0.386***         
  (0.024)          

Constant                             0.602**          
  (0.245)          

------------------------------------------------------
  Observations                         74,935           
Log Likelihood                     -32,423.320        
Akaike Inf. Crit.                  64,880.640         
======================================================
  Note:                      *p<0.1; **p<0.05; ***p<0.01
>

stargazer(model_logit2, type = "text")

=============================================
  Dependent variable:    
  ---------------------------
  LABFORCE          
---------------------------------------------
  AGE                        0.052***          
  (0.012)          

I(AGE2)                    -0.001***         
  (0.0001)          

female                     -0.661***         
  (0.020)          

educ_hs                    0.917***          
  (0.030)          

educ_somecoll              1.491***          
  (0.034)          

educ_college               1.978***          
  (0.036)          

educ_advdeg                2.426***          
  (0.042)          

Constant                   -0.464**          
  (0.237)          

---------------------------------------------
  Observations                74,935           
Log Likelihood            -32,669.470        
Akaike Inf. Crit.         65,354.930         
=============================================
  Note:             *p<0.1; **p<0.05; ***p<0.01

#Given the levels of statistical significance in the logit models, I am stating that education plays a large role on women being in the workforce/laborforce.